"""Erebus Daily Journal job.

At the end of each day, Erebus writes a summary of what it did
to the daily note's Journal section.

Note: Full activity tracking (tool calls, timing) is planned for a future
enhancement. Currently, the journal entry is generated by the AI based on
what it can infer from the daily note and conversation context.
"""

from __future__ import annotations

import asyncio
import logging

from bot.scheduler.base import JobResult, ScheduledJob

logger = logging.getLogger(__name__)

# Timeout for AI operations (seconds)
AI_TIMEOUT = 60.0

# Prompt for Erebus daily journal entry
EREBUS_JOURNAL_PROMPT = """Write a brief journal entry summarizing your activity today.

You are Erebus, the AI assistant. Write a short, first-person journal entry
about what you helped with today.

## Steps:

1. **Read today's daily note** using vault_get_daily_note
2. **Analyze the content:**
   - Count tasks completed (checked items with @todoist tags)
   - Note any journal entries already present
   - Identify projects or themes from the tasks
3. **Write a brief Erebus journal entry** in this format:

### [Current time] - Erebus Log

*A brief summary of today's assistance:*

- [1-2 bullet points about tasks helped with]
- [Any notable observations]

*Pattern noticed: [One brief insight if applicable]*

4. **Add to the daily note:**
   - Read the current content with vault_read_note
   - Find the `## Journal` section
   - Add the entry at the TOP of the Journal section (after the heading)
   - Keep it brief (3-5 lines max)
   - Use vault_write_note with overwrite=true to save

## Example entry:

```markdown
### 23:55 - Erebus Log

*A brief summary of today's assistance:*

- Helped sync 12 tasks between Todoist and the daily note
- Created a new idea seed about "OAuth Integration"

*Pattern noticed: Most productive hours were 9-11am based on task completion times.*
```

Keep entries brief and insightful. Focus on patterns and observations, not just listing actions.
If there was no activity today, write a simple "No significant activity tracked today."
"""


class ErebusJournalJob(ScheduledJob):
    """Writes Erebus's daily journal entry.

    This job runs after the end-of-day sync to add Erebus's own
    reflection on the day's activity.

    Requires:
    - AI (eidolon)
    - Vault
    - Discord user (for DM, optional)
    """

    name = "erebus_journal"
    description = "Erebus writes daily journal entry"
    cron = "58 23 * * *"  # Default: 11:58 PM daily (after end-of-day sync)

    async def run(self) -> JobResult:
        """Write Erebus's journal entry to the daily note."""
        # Check prerequisites
        if not self.context.has_ai:
            return JobResult.skipped("AI not configured")

        if not self.context.has_vault:
            return JobResult.skipped("Vault not configured")

        # Generate and write journal entry
        try:
            logger.info("Writing Erebus journal entry...")

            response = await asyncio.wait_for(
                self.chat(EREBUS_JOURNAL_PROMPT),
                timeout=AI_TIMEOUT,
            )

            if not response:
                return JobResult.failed("AI returned no response for journal entry")

            logger.info("Erebus journal entry written")

            # Optionally send a brief confirmation DM
            if self.context.can_send_dm:
                await self.send_dm(
                    "Erebus journal entry logged. "
                    "My reflections for today have been added to the daily note."
                )

            return JobResult.success("Journal entry written")

        except TimeoutError:
            return JobResult.failed("Journal entry generation timed out")
        except Exception as e:
            logger.exception("Failed to write Erebus journal entry")
            return JobResult.failed(f"Journal entry failed: {e}", error=e)
